FORMAT: 1A
HOST: https://bodacc.herokuapp.com/

# BODACC - Procédures collectives

This API is a simple API to retrieves all BODACC filings related to procédure collectives for a given SIREN.

## Annonces [/questions]

### List of annonces for a given SIREN [GET]

+ Response 200 (application/json)

        {
        "813251303": [
                        {
                        "PCL_TYPE": "Liste des cr\u00e9ances n\u00e9es apr\u00e8s le jugement d'ouverture d'une proc\u00e9dure de redressement judiciaire", 
                        "PCL_DATE": "2019-12-23"}, 
                        {"PCL_TYPE": "D\u00e9p\u00f4t de l'\u00e9tat des cr\u00e9ances", 
                        "PCL_DATE": "2020-01-13"}, 
                        {"PCL_TYPE": "Jugement de cl\u00f4ture pour insuffisance d'actif", 
                        "PCL_DATE": "2020-01-15"}]}